# Generated by Django 2.1.7 on 2019-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastraPresenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=60)),
                ('mac', models.CharField(max_length=60)),
                ('coordenada', models.CharField(max_length=60)),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('preseca', models.BooleanField(default=False)),
            ],
        ),
    ]
