# Generated by Django 2.1.7 on 2019-06-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presenca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastrapresenca',
            old_name='preseca',
            new_name='presenca',
        ),
    ]
